name: Release

on:
  release:
    types: [created,edited,prereleased]
    
jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
       java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.7.8+hotfix.4'
    - name: Update and build apk
      run: |
        flutter upgrade
        flutter pub get
        flutter pub upgrade
        flutter build apk
    
  build-ios:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
       java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.7.8+hotfix.4'
    - name: Update and build ios app
      run: |
        flutter upgrade
        flutter pub get
        flutter pub upgrade
        flutter build ios